# Basic Site Metadata
title: KitchnTabs
description: KitchnTabs food court ordering application.
url: "https://kitchntabs.github.io"
baseurl: ""

# Cayman Theme Configuration
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
- jekyll-remote-theme

# Build Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Cayman Theme Settings
show_downloads: false
google_analytics: # Add your GA tracking ID here if needed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/